apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: entando/entando-component-manager
      context: .
      docker: { }
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: { }
deploy:
  kubectl: { }
profiles:
  - name: jvm
    build:
      artifacts:
        - image: entando/entando-component-manager
          context: .
          docker:
            buildArgs:
              VERSION: "{{ .VERSION}}"

      tagPolicy:
        envTemplate:
          template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
      local: { }
  - name: dev
    build:
      tagPolicy:
        envTemplate:
          template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
      local: { }
    deploy:
      helm:
        releases:
          - name: entando-component-manager
            chartPath: charts/entando-component-manager
            setValueTemplates:
              image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
              image.tag: '{{.DIGEST_HEX}}'
